use std::{collections::HashMap, sync::OnceLock};

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Locale {
    En,
    Tr,
}

impl Locale {
    pub const STORAGE_KEY: &'static str = "hegira-locale";

    pub fn code(self) -> &'static str {
        match self {
            Self::En => "en",
            Self::Tr => "tr",
        }
    }

    pub fn label(self) -> &'static str {
        match self {
            Self::En => "EN",
            Self::Tr => "TR",
        }
    }

    pub fn from_code(code: &str) -> Option<Self> {
        match code {
            "en" => Some(Self::En),
            "tr" => Some(Self::Tr),
            _ => None,
        }
    }

    pub fn toggled(self) -> Self {
        match self {
            Self::En => Self::Tr,
            Self::Tr => Self::En,
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum T {
    Menu,
    Home,
    Users,
    Roles,
    Profile,
    Login,
    Page,
    PageNotFound,
    PageNotFoundDescription,
    Unauthorized,
    UnauthorizedDescription,
    GoHome,
    GoLogin,
    Workspace,
    UsersDescription,
    AddUser,
    RolesDescription,
    AddRole,
    Account,
    SignedIn,
    Settings,
    Logout,
    LoggingOut,
    ConfirmLogout,
    ConfirmLogoutDescription,
    ToggleTheme,
    ToggleLanguage,
    OpenNavigation,
    CloseNavigation,
    ToggleCompactSidebar,
    AllRightsReserved,
    User,
    Products,
    Role,
    RoleName,
    Username,
    Password,
    Search,
    Filter,
    Reset,
    Verification,
    AllUsers,
    AllRoles,
    PermissionStatus,
    RolesWithPermissions,
    RolesWithoutPermissions,
    Verified,
    Pending,
    Action,
    Status,
    Created,
    IdentityUser,
    NoUsersFound,
    NoUsersFoundDescription,
    NoRolesFound,
    NoRolesFoundDescription,
    Edit,
    Delete,
    DeleteRecord,
    DeleteRecordDescriptionPrefix,
    Cancel,
    Previous,
    Next,
    Loading,
    PageLabel,
    EditUser,
    CreateUser,
    EditRole,
    CreateRole,
    EditUserDescription,
    CreateUserDescription,
    EditRoleDescription,
    CreateRoleDescription,
    PasswordKeepCurrent,
    TemporaryPassword,
    VerifiedDescription,
    SaveUser,
    SaveRole,
    Saving,
    UsernameRequired,
    PasswordRequiredForNewUsers,
    PasswordRequired,
    UserNotFound,
    UserAlreadyExists,
    RoleNameRequired,
    RoleNotFound,
    SessionExpired,
    UserUpdated,
    UserUpdatedDescription,
    UserCreated,
    UserCreatedDescription,
    UserSaveFailed,
    UserDeleted,
    UserDeleteFailed,
    ProtectedAdminCannotBeDeleted,
    RoleUpdated,
    RoleCreated,
    RoleDeleted,
    RoleSaveFailed,
    RoleDeleteFailed,
    DeleteRole,
    DeleteRoleDescriptionPrefix,
    ProtectedAdminRoleCannotBeDeleted,
    AddPermissions,
    RolePermissions,
    RolePermissionsDescription,
    UserRolesDescription,
    SavePermissions,
    PermissionsSaved,
    PermissionsSaveFailed,
    HomeDescription,
    Architecture,
    DddReady,
    ArchitectureDescription,
    Frontend,
    RustUi,
    FrontendDescription,
    Delivery,
    SingleBinary,
    DeliveryDescription,
    ProfileDescription,
    ProfilePlaceholder,
    LogoutFailed,
    CreateAccount,
    WelcomeBack,
    CreateWorkspaceAccount,
    SignInWorkspace,
    AuthenticationFailed,
    AccountReady,
    CredentialsRequired,
    AccountCreated,
    InvalidCredentials,
    Creating,
    SigningIn,
    SignIn,
    Or,
    AlreadyHaveAccount,
    NeedAccount,
    LoginHeroKicker,
    LoginHeroTitle,
    LoginHeroDescription,
    ContinueWithGoogle,
    ContinueWithGithub,
    OAuthAuthentication,
    OAuthCompleting,
    CompleteAccount,
    BackToLogin,
    ConnectedAccounts,
    ConnectedAccountsDescription,
    Connect,
    Disconnect,
    InvalidOAuthCallback,
    TotpRequired,
    TotpCode,
    Verify,
    OAuthCancelled,
    ConfirmDisconnect,
    ConfirmDisconnectDescription,
    PermissionIdentityUsers,
    PermissionIdentityUsersCreate,
    PermissionIdentityUsersUpdate,
    PermissionIdentityUsersDelete,
    PermissionIdentityAuthorization,
    PermissionCatalogProducts,
    PermissionCatalogProductsCreate,
    PermissionCatalogProductsUpdate,
    PermissionCatalogProductsDelete,
}

impl T {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Menu => "Menu",
            Self::Home => "Home",
            Self::Users => "Users",
            Self::Roles => "Roles",
            Self::Profile => "Profile",
            Self::Login => "Login",
            Self::Page => "Page",
            Self::PageNotFound => "PageNotFound",
            Self::PageNotFoundDescription => "PageNotFoundDescription",
            Self::Unauthorized => "Unauthorized",
            Self::UnauthorizedDescription => "UnauthorizedDescription",
            Self::GoHome => "GoHome",
            Self::GoLogin => "GoLogin",
            Self::Workspace => "Workspace",
            Self::UsersDescription => "UsersDescription",
            Self::AddUser => "AddUser",
            Self::RolesDescription => "RolesDescription",
            Self::AddRole => "AddRole",
            Self::Account => "Account",
            Self::SignedIn => "SignedIn",
            Self::Settings => "Settings",
            Self::Logout => "Logout",
            Self::LoggingOut => "LoggingOut",
            Self::ConfirmLogout => "ConfirmLogout",
            Self::ConfirmLogoutDescription => "ConfirmLogoutDescription",
            Self::ToggleTheme => "ToggleTheme",
            Self::ToggleLanguage => "ToggleLanguage",
            Self::OpenNavigation => "OpenNavigation",
            Self::CloseNavigation => "CloseNavigation",
            Self::ToggleCompactSidebar => "ToggleCompactSidebar",
            Self::AllRightsReserved => "AllRightsReserved",
            Self::User => "User",
            Self::Products => "Products",
            Self::Role => "Role",
            Self::RoleName => "RoleName",
            Self::Username => "Username",
            Self::Password => "Password",
            Self::Search => "Search",
            Self::Filter => "Filter",
            Self::Reset => "Reset",
            Self::Verification => "Verification",
            Self::AllUsers => "AllUsers",
            Self::AllRoles => "AllRoles",
            Self::PermissionStatus => "PermissionStatus",
            Self::RolesWithPermissions => "RolesWithPermissions",
            Self::RolesWithoutPermissions => "RolesWithoutPermissions",
            Self::Verified => "Verified",
            Self::Pending => "Pending",
            Self::Action => "Action",
            Self::Status => "Status",
            Self::Created => "Created",
            Self::IdentityUser => "IdentityUser",
            Self::NoUsersFound => "NoUsersFound",
            Self::NoUsersFoundDescription => "NoUsersFoundDescription",
            Self::NoRolesFound => "NoRolesFound",
            Self::NoRolesFoundDescription => "NoRolesFoundDescription",
            Self::Edit => "Edit",
            Self::Delete => "Delete",
            Self::DeleteRecord => "DeleteRecord",
            Self::DeleteRecordDescriptionPrefix => "DeleteRecordDescriptionPrefix",
            Self::Cancel => "Cancel",
            Self::Previous => "Previous",
            Self::Next => "Next",
            Self::Loading => "Loading",
            Self::PageLabel => "PageLabel",
            Self::EditUser => "EditUser",
            Self::CreateUser => "CreateUser",
            Self::EditRole => "EditRole",
            Self::CreateRole => "CreateRole",
            Self::EditUserDescription => "EditUserDescription",
            Self::CreateUserDescription => "CreateUserDescription",
            Self::EditRoleDescription => "EditRoleDescription",
            Self::CreateRoleDescription => "CreateRoleDescription",
            Self::PasswordKeepCurrent => "PasswordKeepCurrent",
            Self::TemporaryPassword => "TemporaryPassword",
            Self::VerifiedDescription => "VerifiedDescription",
            Self::SaveUser => "SaveUser",
            Self::SaveRole => "SaveRole",
            Self::Saving => "Saving",
            Self::UsernameRequired => "UsernameRequired",
            Self::PasswordRequiredForNewUsers => "PasswordRequiredForNewUsers",
            Self::PasswordRequired => "PasswordRequired",
            Self::UserNotFound => "UserNotFound",
            Self::UserAlreadyExists => "UserAlreadyExists",
            Self::RoleNameRequired => "RoleNameRequired",
            Self::RoleNotFound => "RoleNotFound",
            Self::SessionExpired => "SessionExpired",
            Self::UserUpdated => "UserUpdated",
            Self::UserUpdatedDescription => "UserUpdatedDescription",
            Self::UserCreated => "UserCreated",
            Self::UserCreatedDescription => "UserCreatedDescription",
            Self::UserSaveFailed => "UserSaveFailed",
            Self::UserDeleted => "UserDeleted",
            Self::UserDeleteFailed => "UserDeleteFailed",
            Self::ProtectedAdminCannotBeDeleted => "ProtectedAdminCannotBeDeleted",
            Self::RoleUpdated => "RoleUpdated",
            Self::RoleCreated => "RoleCreated",
            Self::RoleDeleted => "RoleDeleted",
            Self::RoleSaveFailed => "RoleSaveFailed",
            Self::RoleDeleteFailed => "RoleDeleteFailed",
            Self::DeleteRole => "DeleteRole",
            Self::DeleteRoleDescriptionPrefix => "DeleteRoleDescriptionPrefix",
            Self::ProtectedAdminRoleCannotBeDeleted => "ProtectedAdminRoleCannotBeDeleted",
            Self::AddPermissions => "AddPermissions",
            Self::RolePermissions => "RolePermissions",
            Self::RolePermissionsDescription => "RolePermissionsDescription",
            Self::UserRolesDescription => "UserRolesDescription",
            Self::SavePermissions => "SavePermissions",
            Self::PermissionsSaved => "PermissionsSaved",
            Self::PermissionsSaveFailed => "PermissionsSaveFailed",
            Self::HomeDescription => "HomeDescription",
            Self::Architecture => "Architecture",
            Self::DddReady => "DddReady",
            Self::ArchitectureDescription => "ArchitectureDescription",
            Self::Frontend => "Frontend",
            Self::RustUi => "RustUi",
            Self::FrontendDescription => "FrontendDescription",
            Self::Delivery => "Delivery",
            Self::SingleBinary => "SingleBinary",
            Self::DeliveryDescription => "DeliveryDescription",
            Self::ProfileDescription => "ProfileDescription",
            Self::ProfilePlaceholder => "ProfilePlaceholder",
            Self::LogoutFailed => "LogoutFailed",
            Self::CreateAccount => "CreateAccount",
            Self::WelcomeBack => "WelcomeBack",
            Self::CreateWorkspaceAccount => "CreateWorkspaceAccount",
            Self::SignInWorkspace => "SignInWorkspace",
            Self::AuthenticationFailed => "AuthenticationFailed",
            Self::AccountReady => "AccountReady",
            Self::CredentialsRequired => "CredentialsRequired",
            Self::AccountCreated => "AccountCreated",
            Self::InvalidCredentials => "InvalidCredentials",
            Self::Creating => "Creating",
            Self::SigningIn => "SigningIn",
            Self::SignIn => "SignIn",
            Self::Or => "Or",
            Self::AlreadyHaveAccount => "AlreadyHaveAccount",
            Self::NeedAccount => "NeedAccount",
            Self::LoginHeroKicker => "LoginHeroKicker",
            Self::LoginHeroTitle => "LoginHeroTitle",
            Self::LoginHeroDescription => "LoginHeroDescription",
            Self::ContinueWithGoogle => "ContinueWithGoogle",
            Self::ContinueWithGithub => "ContinueWithGithub",
            Self::OAuthAuthentication => "OAuthAuthentication",
            Self::OAuthCompleting => "OAuthCompleting",
            Self::CompleteAccount => "CompleteAccount",
            Self::BackToLogin => "BackToLogin",
            Self::ConnectedAccounts => "ConnectedAccounts",
            Self::ConnectedAccountsDescription => "ConnectedAccountsDescription",
            Self::Connect => "Connect",
            Self::Disconnect => "Disconnect",
            Self::InvalidOAuthCallback => "InvalidOAuthCallback",
            Self::TotpRequired => "TotpRequired",
            Self::TotpCode => "TotpCode",
            Self::Verify => "Verify",
            Self::OAuthCancelled => "OAuthCancelled",
            Self::ConfirmDisconnect => "ConfirmDisconnect",
            Self::ConfirmDisconnectDescription => "ConfirmDisconnectDescription",
            Self::PermissionIdentityUsers => "Permission.Identity.Users",
            Self::PermissionIdentityUsersCreate => "Permission.Identity.Users.Create",
            Self::PermissionIdentityUsersUpdate => "Permission.Identity.Users.Update",
            Self::PermissionIdentityUsersDelete => "Permission.Identity.Users.Delete",
            Self::PermissionIdentityAuthorization => "Permission.Identity.Authorization",
            Self::PermissionCatalogProducts => "Permission.Catalog.Products",
            Self::PermissionCatalogProductsCreate => "Permission.Catalog.Products.Create",
            Self::PermissionCatalogProductsUpdate => "Permission.Catalog.Products.Update",
            Self::PermissionCatalogProductsDelete => "Permission.Catalog.Products.Delete",
        }
    }
}

pub fn translate(locale: Locale, key: T) -> &'static str {
    let key_name = key.as_str();
    resources(locale)
        .get(key_name)
        .map(String::as_str)
        .unwrap_or(key_name)
}

fn resources(locale: Locale) -> &'static HashMap<String, String> {
    static EN: OnceLock<HashMap<String, String>> = OnceLock::new();
    static TR: OnceLock<HashMap<String, String>> = OnceLock::new();

    match locale {
        Locale::En => EN.get_or_init(|| parse_resource(include_str!("resources/en.json"))),
        Locale::Tr => TR.get_or_init(|| parse_resource(include_str!("resources/tr.json"))),
    }
}

fn parse_resource(source: &str) -> HashMap<String, String> {
    serde_json::from_str(source).expect("localization resource must be valid JSON")
}
