[package]
name = "identity_leptos"
version = "0.3.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[dependencies]
identity_application = { path = "../application", optional = true }
identity_application_contracts = { path = "../application_contracts" }
identity_domain_shared = { path = "../domain_shared" }
leptos_support = { path = "../../../crates/leptos_support", default-features = false }

icons = { version = "0.18.3", features = ["leptos"] }
leptos = { version = "0.8.19" }
leptos_router = { version = "0.8.13" }
serde_json = "1.0.145"
uuid = { version = "1.23.2", features = ["serde", "js"] }
web-sys = { version = "0.3.91", features = ["Location", "Storage", "Window"] }

[features]
default = ["db-postgres", "db-sqlite"]
db-postgres = []
db-sqlite = []
hydrate = [
    "leptos/hydrate",
    "leptos_support/hydrate",
]
ssr = [
    "dep:identity_application",
    "identity_application/ssr",
    "leptos/ssr",
    "leptos_support/ssr",
    "leptos_router/ssr",
]
wasm-split = []
