[package]
name = "runtime"
version = "0.3.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.52.3", features = ["rt-multi-thread", "macros", "fs", "signal"] }
tracing = "0.1.44"

[features]
default = []
