[package]
name = "app_presentation"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
app_application.workspace = true
app_application_contracts.workspace = true
app_domain_shared.workspace = true
http_support.workspace = true
axum.workspace = true
serde.workspace = true
tower-http = { version = "0.7.0", features = ["timeout"] }

[features]
default = []
db-postgres = []
db-sqlite = []
