schema = 2
application = "{{application_name}}"

[framework]
repository = "{{framework_repository}}"
version = "{{framework_version}}"

[selection]
databases = ["{{database_adapter}}"]
clients = ["{{client_adapter}}"]

[composition]
components = []

[composition.package]
id = "{{package_id}}"
version = "{{package_version}}"
