#[cfg(feature = "ssr")]
pub mod audit;
#[cfg(feature = "ssr")]
pub mod cache;
pub mod config;
#[cfg(feature = "ssr")]
pub mod db;
#[cfg(feature = "ssr")]
pub mod identity;
#[cfg(feature = "ssr")]
pub mod mail;
#[cfg(feature = "ssr")]
pub mod search;
#[cfg(feature = "ssr")]
pub mod security;
#[cfg(feature = "ssr")]
pub mod settings;
#[cfg(feature = "ssr")]
pub mod storage;
#[cfg(feature = "db-postgres")]
pub mod testing;
