[package]
name = "web"
version = "0.1.1"
edition = "2024"
license = "Apache-2.0"
publish = false

[lib]
path = "src/mod.rs"

[dependencies]
application = { path = "../application", optional = true }
application_contracts = { path = "../application_contracts" }
domain_shared = { path = "../domain_shared" }
presentation = { path = "../presentation", optional = true, default-features = false }

icons = { version = "0.18.3", features = ["leptos"] }
leptos = { version = "0.8.19" }
leptos_meta = { version = "0.8.6" }
leptos_router = { version = "0.8.13" }
leptos_ui = "0.3.22"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
strum = { version = "0.28.0", features = ["derive"] }
tw_merge = { version = "0.1.21", features = ["variant"] }
validator = "0.20.0"
uuid = { version = "1.23.2", features = ["serde", "js"] }
web-sys = { version = "0.3.91", features = ["Document", "DomTokenList", "Element", "Event", "HtmlDocument", "HtmlElement", "Location", "Storage", "Window"] }

[features]
default = ["db-postgres", "db-sqlite"]
db-postgres = ["presentation/db-postgres"]
db-sqlite = ["presentation/db-sqlite"]
hydrate = ["leptos/hydrate"]
ssr = [
    "dep:application",
    "dep:presentation",
    "application/ssr",
    "presentation/ssr",
    "leptos/ssr",
    "leptos_meta/ssr",
    "leptos_router/ssr",
]
wasm-split = []
