[package]
name = "application"
version = "0.3.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[dependencies]
background_jobs = { path = "../background_jobs" }
identity_application = { path = "../../modules/identity/application" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"

[features]
ssr = ["identity_application/ssr"]

[dev-dependencies]
tokio = { version = "1.52.3", features = ["macros", "rt"] }
