schema = 1
id = "layered-leptos-identity"
source = "applications/layered"
include = ["Cargo.toml", "Dockerfile", "apps"]
requires = ["layered-base"]

[[framework_dependencies]]
manifest = "Cargo.toml"
name = "audit"
path = "crates/audit"

[[framework_dependencies]]
manifest = "Cargo.toml"
name = "background_jobs"
path = "crates/background_jobs"

[[framework_dependencies]]
manifest = "Cargo.toml"
name = "cache"
path = "crates/cache"

[[framework_dependencies]]
manifest = "Cargo.toml"
name = "configuration"
path = "crates/configuration"

[[framework_dependencies]]
manifest = "Cargo.toml"
name = "http_support"
path = "crates/http_support"

[[framework_dependencies]]
manifest = "Cargo.toml"
name = "identity_application"
path = "modules/identity/application"
default_features = false

[[framework_dependencies]]
manifest = "Cargo.toml"
name = "identity_application_contracts"
path = "modules/identity/application_contracts"

[[framework_dependencies]]
manifest = "Cargo.toml"
name = "identity_domain"
path = "modules/identity/domain"

[[framework_dependencies]]
manifest = "Cargo.toml"
name = "identity_domain_shared"
path = "modules/identity/domain_shared"

[[framework_dependencies]]
manifest = "Cargo.toml"
name = "identity_http"
path = "modules/identity/http"
default_features = false

[[framework_dependencies]]
manifest = "Cargo.toml"
name = "identity_leptos"
path = "modules/identity/leptos"
default_features = false

[[framework_dependencies]]
manifest = "Cargo.toml"
name = "identity_sqlx"
path = "modules/identity/sqlx"
default_features = false

[[framework_dependencies]]
manifest = "Cargo.toml"
name = "leptos_support"
path = "crates/leptos_support"
default_features = false

[[framework_dependencies]]
manifest = "Cargo.toml"
name = "mail"
path = "crates/mail"

[[framework_dependencies]]
manifest = "Cargo.toml"
name = "observability"
path = "crates/observability"

[[framework_dependencies]]
manifest = "Cargo.toml"
name = "persistence"
path = "crates/persistence"
default_features = false

[[framework_dependencies]]
manifest = "Cargo.toml"
name = "platform_core"
path = "crates/platform_core"

[[framework_dependencies]]
manifest = "Cargo.toml"
name = "runtime"
path = "crates/runtime"

[[framework_dependencies]]
manifest = "Cargo.toml"
name = "search"
path = "crates/search"
default_features = false

[[framework_dependencies]]
manifest = "Cargo.toml"
name = "security"
path = "crates/security"

[[framework_dependencies]]
manifest = "Cargo.toml"
name = "settings"
path = "crates/settings"

[[framework_dependencies]]
manifest = "Cargo.toml"
name = "storage"
path = "crates/storage"
default_features = false
